version: '3.4'
services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.26.6
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    environment:
      - QUERY_DEFAULTS_LIMIT=${QUERY_DEFAULTS_LIMIT}
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=${AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED}
      - PERSISTENCE_DATA_PATH=${PERSISTENCE_DATA_PATH}
      - DEFAULT_VECTORIZER_MODULE=${DEFAULT_VECTORIZER_MODULE}
      - ENABLE_API_BASED_MODULES=${ENABLE_API_BASED_MODULES}
      - CLUSTER_HOSTNAME=${CLUSTER_HOSTNAME}
      - ENABLE_MODULES=${ENABLE_MODULES}
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data: